[package]
name = "deepseek-api"
version = "0.1.0"
edition = "2024"


[dependencies]
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
async-stream = "0.3.6"
futures = "0.3.31"
